// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WpfSnippets
{
    internal sealed partial class Vsix
    {
        public const string Id = "e53abfaf-e0c5-4c8d-8091-670493a8120e";
        public const string Name = "Wpf Snippets";
        public const string Description = @"WPF snippets for base classes, properties notifiying the view and sync/async commands";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Niklas Hempel";
        public const string Tags = "WPF, snippet, command, property, async";
    }
}
