// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WpfSnippets
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string WpfSnippetsString = "04b953c9-8348-4aaa-9b37-c3f1964d9d1a";
        public static Guid WpfSnippets = new Guid(WpfSnippetsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int WpfSnippetsMenu = 0x0001;
        public const int WpfSnippetsSettings = 0x0002;
        public const int WpfSnippetsHelp = 0x0003;
        public const int WpfSnippetsOptions = 0x0100;
        public const int FirstHelp = 0x0101;
    }
}