name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      RepositoryUrl: 'https://github.com/${{ github.repository }}'
      Configuration: Release
      SolutionPath: src\WpfSnippets.sln
      VsixManifestPath: src\WpfSnippets\source.extension.vsixmanifest

    steps:
    - name: Checkout Code
      uses: actions/checkout@master
             
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Restore NuGet Packages
      run: nuget restore $env:SolutionPath
      
    - name: Build extension
      run: msbuild $env:SolutionPath /t:Rebuild
      env: 
        DeployExtension: False
