name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Solution
      run: |
        msbuild.exe WpfSnippets.sln /nologo /nr:false /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:TargetFrameworkVersion="v4.7.2"

    - name: Test
      run: dotnet test --no-build --verbosity normal
